### PR TITLE
Question 3 implementation of alarm class

### PR DESCRIPTION
**Pull request by IanMair**
Implemented question 3 Alarm's methods waitUntil and ISR
Added KThreadTimer class to package KThread and waitTime

### CODE REVIEW

**Comment by baugarten** [comment]
You changed 262 files... you should add only the files that are important, not .metadata/*, etc

**Comment by IanMair** [comment]
I realized that after I did it. How do I undo my git retardedness?

**Comment by IanMair** [comment]
Should I rollback and then just commit the two files I edited?

**Comment by baugarten** [comment]
done :)

**Comment by IanMair** [comment]
Thank you! Damn, you are good.

Can you sit down and educate me about the finer points of git sometime soon?

**Comment by baugarten** [comment]
Of course! Git is awesome

**Pull request merged**
